version: "3.8"

services:
  web_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app/frontend
      - '/app/frontend/node_modules'

  api_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app/backend
      - '/app/backend/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
